services:
  - type: web
    name: finwise-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 5000
